server:
  port: 1000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: "*"